use_frameworks!

platform :ios, '10.0'

target 'ZLPermission_Example' do
  pod 'ZLPermission', :path => '../'

  target 'ZLPermission_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
